### ISSUE TITLE
This project needs a license

### ISSUE THREAD

**Issue by mvicomoya** [alfremedpal/board-game-picker#3]
Hey @alfremedpal,

First I wanted to thank you for writing this app, it's just great and I wanted to contribute by adding a patch to add an option to select the desired number of players (not minimum or maximum, but how many players are going to play the game). I also wanted to host an instance locally for me to use.

However, one thing I noticed is that you didn't add any license at all.

Would you mind to add a license so that others know how can they contribute and use your software?

Interesting read about picking a license: https://blog.codinghorror.com/pick-a-license-any-license/

Thanks!

**Comment by alfremedpal** [comment]
Hey @mvicomoya !

Thank you for the comments, and I'm glad you found this little project useful 😄 . You are definitely right, I should add a license, I can't believe I forgot about it! I'll be adding it this week and notifying you (spoiler alert: it will be a very permissive license like MIT or GNU GPLv3). Thanks again.

**Comment by alfremedpal** [comment]
@mvicomoya forget about what I said about adding the license during this week haha, it's already up. The license is [MIT](https://choosealicense.com/licenses/mit/) so you are free to do pretty much anything you want. I'll be waiting for your patch 😉 .

**Comment by mvicomoya** [comment]
Awesome! Thanks a lot @alfremedpal!
